#pragma once

/* Production portal shell — served from flash, data via /api JSON. */

static const char WEB_APP_HTML[] =
"<!DOCTYPE html><html lang=\"en\"><head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>ICC Gateway</title>"
"<style>"
":root{--bg:#0a101c;--panel:#121a2b;--panel2:#161f32;--line:#243049;--text:#e8eef8;--muted:#8b9bb4;"
"--accent:#1ec8a5;--accent2:#3d8bfd;--danger:#ff6b6b;--ok:#1ec8a5;--warn:#f0b429;"
"--radius:12px;--shadow:0 8px 28px rgba(0,0,0,.28)}"
"*{box-sizing:border-box}"
"body{margin:0;font-family:'Segoe UI',ui-sans-serif,system-ui,-apple-system,sans-serif;"
"background:radial-gradient(900px 480px at 8% -8%,#16324a 0%,transparent 55%),"
"radial-gradient(700px 420px at 100% 0%,#12263a 0%,transparent 48%),var(--bg);"
"color:var(--text);min-height:100vh}"
"header.app{position:sticky;top:0;z-index:30;backdrop-filter:blur(14px);"
"background:rgba(10,16,28,.88);border-bottom:1px solid var(--line)}"
".wrap{max-width:920px;margin:0 auto;padding:0 1.25rem}"
".brand{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.85rem 0 .35rem}"
".logo{display:flex;align-items:center;gap:.7rem}"
".mark{width:34px;height:34px;border-radius:9px;background:linear-gradient(135deg,var(--accent),#0e8f9a);"
"box-shadow:0 0 0 1px rgba(30,200,165,.35),0 6px 18px rgba(30,200,165,.22);flex:0 0 auto}"
".logo h1{font-size:1.02rem;margin:0;font-weight:650;letter-spacing:.01em}"
".logo p{margin:.1rem 0 0;color:var(--muted);font-size:.74rem}"
".pill{font-size:.7rem;padding:.26rem .6rem;border-radius:999px;border:1px solid var(--line);"
"background:rgba(255,255,255,.03);color:var(--muted);white-space:nowrap}"
".pill.ok{color:var(--ok);border-color:rgba(30,200,165,.35);background:rgba(30,200,165,.08)}"
".pill.bad{color:var(--danger);border-color:rgba(255,107,107,.35);background:rgba(255,107,107,.08)}"
".pill.warn{color:var(--warn);border-color:rgba(240,180,41,.35);background:rgba(240,180,41,.08)}"
"nav.tabs{display:flex;gap:.25rem;overflow:auto;padding:.15rem 0 .85rem}"
"nav.tabs button{border:0;background:transparent;color:var(--muted);padding:.5rem .8rem;"
"border-radius:999px;font-weight:600;font-size:.84rem;cursor:pointer;white-space:nowrap}"
"nav.tabs button:hover{color:var(--text)}"
"nav.tabs button.active{background:rgba(30,200,165,.14);color:var(--accent)}"
"main{padding:1.75rem 0 2.25rem}"
".grid{display:grid;gap:.9rem}"
".cards{display:grid;gap:.9rem;grid-template-columns:repeat(2,minmax(0,1fr))}"
"@media(min-width:720px){.cards{grid-template-columns:repeat(4,minmax(0,1fr))}}"
".card{background:linear-gradient(180deg,rgba(255,255,255,.028),transparent),var(--panel);"
"border:1px solid var(--line);border-radius:var(--radius);padding:1rem 1.05rem;box-shadow:var(--shadow)}"
".card h2{margin:0 0 .7rem;font-size:.68rem;letter-spacing:.09em;text-transform:uppercase;"
"color:var(--muted);font-weight:700}"
".card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem;margin-bottom:.85rem}"
".card-head h2{margin:0}"
".metric{font-size:1.35rem;font-weight:700;letter-spacing:-.02em;margin:0 0 .2rem;line-height:1.15}"
".metric small{font-size:.82rem;color:var(--muted);font-weight:500}"
"dl.kv{display:grid;grid-template-columns:minmax(7.5rem,9.5rem) 1fr;gap:.4rem .9rem;margin:0}"
"dl.kv dt{color:var(--muted);font-size:.8rem;padding:.12rem 0}"
"dl.kv dd{margin:0;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.82rem;"
"word-break:break-all;padding:.12rem 0;color:var(--text)}"
"label{display:block;color:var(--muted);font-size:.76rem;margin:.65rem 0 .25rem;font-weight:600}"
"input,select{width:100%;padding:.68rem .75rem;border-radius:9px;border:1px solid var(--line);"
"background:#0d1524;color:var(--text);font-size:.92rem}"
"input:focus,select:focus{outline:2px solid rgba(30,200,165,.35);border-color:rgba(30,200,165,.5)}"
".toolbar{display:flex;flex-wrap:wrap;gap:.55rem;align-items:center;margin:0 0 1rem}"
".toolbar .btn{margin:0;width:auto;min-width:0;flex:0 0 auto}"
".row{display:flex;gap:.55rem;align-items:stretch;flex-wrap:wrap}.row>*{flex:1 1 140px}"
"button.btn{display:inline-flex;align-items:center;justify-content:center;gap:.45rem;"
"width:100%;padding:.68rem .9rem;border-radius:9px;border:0;cursor:pointer;"
"font-weight:650;font-size:.88rem;background:linear-gradient(135deg,var(--accent),#149e90);"
"color:#041512;margin-top:.75rem;transition:transform .12s ease,opacity .15s ease,box-shadow .15s ease}"
"button.btn:hover:not(:disabled){transform:translateY(-1px);box-shadow:0 6px 16px rgba(30,200,165,.22)}"
"button.btn:active:not(:disabled){transform:translateY(0)}"
"button.btn.secondary{background:var(--panel2);color:var(--text);border:1px solid var(--line);"
"box-shadow:none}"
"button.btn.secondary:hover:not(:disabled){background:#1b263c;box-shadow:none}"
"button.btn.danger{background:linear-gradient(135deg,#ff6b6b,#d94848);color:#fff}"
"button.btn:disabled{opacity:.55;cursor:wait;transform:none;box-shadow:none}"
"button.btn .spin{width:.85rem;height:.85rem;border:2px solid currentColor;border-right-color:transparent;"
"border-radius:50%;display:none;animation:spin .7s linear infinite}"
"button.btn.busy .spin{display:inline-block}button.btn.busy .label{opacity:.9}"
"button.btn.sm{width:auto;margin:0;padding:.42rem .7rem;font-size:.78rem}"
".sniff-log{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.72rem;"
"line-height:1.45;background:#0b1220;border:1px solid var(--line);border-radius:10px;"
"padding:.65rem .75rem;max-height:min(70vh,560px);overflow:auto;white-space:pre-wrap;word-break:break-word;"
"color:#c8d4e8}"
".sniff-log .rx{color:#7dffa8}.sniff-log .tx{color:#7ec8ff}.sniff-log .evt{color:#ffd27d}"
".sniff-log .meta{color:#7a869c}"
".sniff-toolbar{display:flex;flex-wrap:wrap;gap:.5rem;align-items:center;margin-bottom:.75rem}"
".sniff-toolbar label.check{margin:0}"
".pill.on{background:rgba(30,200,165,.18);color:var(--accent)}"
".device .btn{width:auto;margin:0;flex:0 0 auto;align-self:center}"
"@keyframes spin{to{transform:rotate(360deg)}}"
".check{display:flex;align-items:center;gap:.5rem;margin-top:.6rem;color:var(--muted);font-size:.84rem}"
".check input{width:auto;margin:0}"
".member-pick{max-height:11rem;overflow:auto;border:1px solid var(--line);border-radius:10px;"
"padding:.35rem .55rem;margin-top:.35rem;background:rgba(255,255,255,.35)}"
".member-pick .check{margin-top:.35rem}"
".form-block.hidden{display:none}"
".hint{color:var(--muted);font-size:.78rem;margin:.5rem 0 0;line-height:1.45}"
".banner{padding:.8rem .95rem;border-radius:10px;border:1px solid var(--line);background:rgba(61,139,253,.08);"
"color:#cfe0ff;margin-bottom:.9rem;font-size:.88rem;line-height:1.4}"
".banner.ok{background:rgba(30,200,165,.08);border-color:rgba(30,200,165,.3);color:#baf7e8}"
".banner.warn{background:rgba(240,180,41,.08);border-color:rgba(240,180,41,.3);color:#ffe6a8}"
".banner.join{display:flex;align-items:center;justify-content:space-between;gap:.75rem;flex-wrap:wrap}"
".banner.join .count{font-family:ui-monospace,Menlo,monospace;font-weight:700;font-size:1.05rem}"
".empty{text-align:center;padding:2rem 1rem;color:var(--muted);border:1px dashed var(--line);"
"border-radius:10px;background:rgba(255,255,255,.015)}"
".empty strong{display:block;color:var(--text);font-size:1rem;margin-bottom:.3rem}"
".device{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:.85rem .55rem;"
"border-bottom:1px solid var(--line);cursor:pointer;border-radius:8px;transition:background .12s}"
".device:hover{background:rgba(255,255,255,.03)}"
".device:last-child{border-bottom:0}"
".device .id{font-family:ui-monospace,Menlo,monospace;font-size:.8rem}"
".device .title{font-weight:650;font-size:.92rem;margin-bottom:.15rem;display:flex;align-items:center;gap:.45rem}"
".device .meta{color:var(--muted);font-size:.76rem;margin-top:.12rem}"
".device .kind{color:var(--text);font-size:.78rem;margin-top:.2rem;font-weight:550}"
".device .vals{display:flex;flex-wrap:wrap;gap:.35rem;margin-top:.4rem}"
".chip{font-size:.72rem;padding:.18rem .45rem;border-radius:6px;background:rgba(30,200,165,.1);"
"border:1px solid rgba(30,200,165,.22);color:#baf7e8}"
".sig{display:inline-flex;align-items:flex-end;gap:2px;height:12px;flex:0 0 auto;vertical-align:middle}"
".sig i{display:block;width:3px;border-radius:1px;background:rgba(139,155,180,.28)}"
".sig i:nth-child(1){height:3px}.sig i:nth-child(2){height:5px}.sig i:nth-child(3){height:8px}.sig i:nth-child(4){height:11px}"
".sig[data-lvl=\"1\"] i:nth-child(-n+1),.sig[data-lvl=\"2\"] i:nth-child(-n+2),"
".sig[data-lvl=\"3\"] i:nth-child(-n+3),.sig[data-lvl=\"4\"] i:nth-child(-n+4){background:var(--accent)}"
".sig.weak[data-lvl=\"1\"] i:nth-child(-n+1){background:var(--warn)}"
".sig.none i{background:rgba(139,155,180,.18)}"
".sig-wrap{display:inline-flex;align-items:center;gap:.35rem;color:var(--muted);font-size:.7rem;"
"font-family:ui-monospace,Menlo,monospace;font-weight:500}"
".progress{height:3px;background:#1a2438;border-radius:99px;overflow:hidden;margin-top:.65rem}"
".progress>i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--accent),var(--accent2));"
"transition:width .3s ease}"
".hidden{display:none!important}"
"#toasts{position:fixed;right:1rem;bottom:1rem;z-index:50;display:flex;flex-direction:column;gap:.5rem;"
"max-width:min(360px,calc(100vw - 2rem));pointer-events:none}"
".toast{pointer-events:auto;padding:.75rem .9rem;border-radius:10px;border:1px solid var(--line);"
"background:rgba(18,26,43,.96);box-shadow:var(--shadow);font-size:.86rem;line-height:1.35;"
"animation:toastIn .2s ease;display:flex;gap:.65rem;align-items:flex-start}"
".toast.ok{border-color:rgba(30,200,165,.4)}.toast.err{border-color:rgba(255,107,107,.45)}"
".toast.warn{border-color:rgba(240,180,41,.4)}"
".toast .dot{width:.55rem;height:.55rem;border-radius:50%;margin-top:.35rem;flex:0 0 auto;background:var(--accent)}"
".toast.err .dot{background:var(--danger)}.toast.warn .dot{background:var(--warn)}"
"@keyframes toastIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}"
".modal-backdrop{position:fixed;inset:0;z-index:40;background:rgba(4,8,16,.62);backdrop-filter:blur(4px);"
"display:flex;align-items:flex-end;justify-content:center;padding:1rem}"
"@media(min-width:640px){.modal-backdrop{align-items:center}}"
".modal{width:min(520px,100%);max-height:min(88vh,720px);overflow:auto;background:var(--panel);"
"border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow);padding:1.1rem 1.15rem 1.2rem}"
".modal h3{margin:0 0 .35rem;font-size:1.05rem}"
".modal .sub{color:var(--muted);font-size:.78rem;margin:0 0 1rem;font-family:ui-monospace,Menlo,monospace}"
".modal-actions{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:1rem}"
".modal-actions .btn{margin-top:0;flex:1 1 auto;width:auto}"
".btn-test{margin:1rem 0 0;padding:.85rem .9rem;border:1px solid var(--line);border-radius:10px;"
"background:rgba(255,255,255,.02)}"
".btn-test h4,.btn-modes h4{margin:0 0 .35rem;font-size:.88rem;font-weight:650}"
".btn-test .hint,.btn-modes .hint{margin:0 0 .75rem;font-size:.76rem;color:var(--muted);line-height:1.35}"
".btn-modes{margin:1rem 0 0;padding:.85rem .9rem;border:1px solid var(--line);border-radius:10px;"
"background:rgba(255,255,255,.02)}"
".btn-mode-row{display:flex;align-items:center;justify-content:space-between;gap:.5rem;"
"padding:.4rem 0;border-bottom:1px solid rgba(255,255,255,.04);flex-wrap:wrap}"
".btn-mode-row:last-child{border-bottom:0}"
".btn-mode-row label{margin:0;font-size:.78rem;font-weight:550;flex:0 0 auto;min-width:4.2rem;color:var(--muted)}"
".btn-mode-row input[type=text]{flex:1 1 7rem;min-width:6rem;margin:0;padding:.4rem .55rem;font-size:.78rem}"
".btn-mode-row select{width:auto;min-width:8.5rem;margin:0;padding:.4rem .55rem;font-size:.78rem;flex:0 0 auto}"
"#mdTarget{min-height:8.5rem;height:auto}"
".btn-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(4.2rem,1fr));gap:.4rem}"
".btn-pad{appearance:none;border:1px solid var(--line);border-radius:8px;background:#121a2b;"
"color:var(--muted);padding:.65rem .3rem;font-size:.72rem;font-weight:600;text-align:center;"
"transition:background .15s,border-color .15s,color .15s,transform .12s}"
".btn-pad.on{background:rgba(30,200,165,.18);border-color:rgba(30,200,165,.55);color:#baf7e8;"
"transform:scale(1.04)}"
".btn-log{margin:.7rem 0 0;padding:0;list-style:none;max-height:7.5rem;overflow:auto;"
"font-size:.74rem;font-family:ui-monospace,Menlo,monospace;color:var(--muted)}"
".btn-log li{padding:.2rem 0;border-bottom:1px solid rgba(255,255,255,.04)}"
".btn-log li:first-child{color:var(--text);font-weight:600}"
"footer{color:#66748c;text-align:center;font-size:.7rem;padding:0 1rem 1.75rem}"
"@media(max-width:560px){.cards{grid-template-columns:1fr 1fr}"
"dl.kv{grid-template-columns:minmax(6.5rem,8rem) 1fr}.brand{align-items:flex-start}}"
"@media(max-width:420px){.cards{grid-template-columns:1fr}}"
"</style></head><body>"
"<header class=\"app\"><div class=\"wrap\">"
"<div class=\"brand\"><div class=\"logo\"><div class=\"mark\"></div><div>"
"<h1>ICC Gateway</h1><p>Zigbee · HomeKit-ready bridge</p></div></div>"
"<div id=\"topPill\" class=\"pill\">…</div></div>"
"<nav class=\"tabs\" id=\"tabs\">"
"<button type=\"button\" data-tab=\"overview\" class=\"active\">Overview</button>"
"<button type=\"button\" data-tab=\"network\">Zigbee</button>"
"<button type=\"button\" data-tab=\"devices\">Devices</button>"
"<button type=\"button\" data-tab=\"groups\">Grouped devices</button>"
"<button type=\"button\" data-tab=\"sniff\">Sniffer</button>"
"<button type=\"button\" data-tab=\"system\">System</button>"
"</nav></div></header>"
"<main class=\"wrap\">"
"<section id=\"setup\" class=\"hidden\">"
"<div class=\"banner\">Connect this gateway to your home Wi‑Fi. SoftAP setup turns off automatically after you join.</div>"
"<div class=\"card\"><h2>Home Wi‑Fi</h2>"
"<label>Nearby networks</label><div class=\"row\">"
"<select id=\"scan\"><option value=\"\">— Scan to discover —</option></select>"
"<button type=\"button\" class=\"btn secondary\" id=\"scanBtn\" style=\"margin-top:0;flex:0 0 auto\">"
"<span class=\"spin\"></span><span class=\"label\">Scan</span></button></div>"
"<div class=\"progress\"><i id=\"scanBar\"></i></div>"
"<p class=\"hint\" id=\"scanStatus\">Scanning briefly pauses SoftAP on some phones — reconnect if needed.</p>"
"<label for=\"ssid\">Network name (SSID)</label>"
"<input id=\"ssid\" maxlength=\"32\" autocomplete=\"off\" autocapitalize=\"none\" placeholder=\"Your home Wi‑Fi\">"
"<label for=\"password\">Password</label>"
"<input id=\"password\" type=\"password\" maxlength=\"63\" placeholder=\"Leave empty if open\">"
"<label class=\"check\"><input type=\"checkbox\" id=\"showPass\"> Show password</label>"
"<button type=\"button\" class=\"btn\" id=\"saveWifi\"><span class=\"spin\"></span><span class=\"label\">Save &amp; connect</span></button>"
"<p class=\"hint\" id=\"wifiMsg\"></p>"
"</div></section>"
"<section id=\"app\">"
"<div id=\"view-overview\" class=\"grid\">"
"<div class=\"cards\">"
"<div class=\"card\"><h2>Zigbee radio</h2><div class=\"metric\" id=\"mIcc\">—</div>"
"<p class=\"hint\" id=\"mIccSub\">ICC / ASH / EZSP</p></div>"
"<div class=\"card\"><h2>Network</h2><div class=\"metric\" id=\"mNet\">—</div>"
"<p class=\"hint\" id=\"mNetSub\">channel · PAN</p></div>"
"<div class=\"card\"><h2>Devices</h2><div class=\"metric\" id=\"mDev\">0</div>"
"<p class=\"hint\">joined on the NCP</p></div>"
"<div class=\"card\"><h2>Wi‑Fi</h2><div class=\"metric\" id=\"mWifi\"><small id=\"mWifiIp\">—</small></div>"
"<p class=\"hint\" id=\"mWifiSub\">home network</p></div>"
"</div>"
"<div class=\"card\"><h2>Coordinator identity</h2><dl class=\"kv\" id=\"overviewKv\"></dl></div>"
"<div class=\"card\"><h2>HomeKit</h2><dl class=\"kv\" id=\"hkKv\"></dl>"
"<p class=\"hint\">In the Home app: Add Accessory → More options → ICC Gateway. Use the setup code below.</p>"
"</div>"
"</div>"
"<div id=\"view-network\" class=\"grid hidden\">"
"<div class=\"card\"><h2>Zigbee network</h2>"
"<div id=\"netBanner\" class=\"banner\">Loading…</div>"
"<dl class=\"kv\" id=\"netKv\"></dl>"
"<div id=\"formBox\">"
"<label>Channel (11–26)</label>"
"<select id=\"ch\">"
"<option value=\"11\">11</option><option value=\"12\">12</option><option value=\"13\">13</option>"
"<option value=\"14\">14</option><option value=\"15\" selected>15</option><option value=\"16\">16</option>"
"<option value=\"17\">17</option><option value=\"18\">18</option><option value=\"19\">19</option>"
"<option value=\"20\">20</option><option value=\"21\">21</option><option value=\"22\">22</option>"
"<option value=\"23\">23</option><option value=\"24\">24</option><option value=\"25\">25</option>"
"<option value=\"26\">26</option></select>"
"<label>Transmit power (dBm)</label>"
"<select id=\"tx\"><option value=\"0\">0</option><option value=\"5\">5</option>"
"<option value=\"8\" selected>8</option><option value=\"20\">20</option></select>"
"<button type=\"button\" class=\"btn\" id=\"formBtn\"><span class=\"spin\"></span><span class=\"label\">Create Zigbee network</span></button>"
"<p class=\"hint\">Forms a secured coordinator network on the ICC-1. An existing network is left first.</p>"
"</div>"
"<div class=\"toolbar\" id=\"netActions\">"
"<button type=\"button\" class=\"btn\" id=\"permitBtn\"><span class=\"spin\"></span><span class=\"label\">Permit join 120s</span></button>"
"<button type=\"button\" class=\"btn secondary\" id=\"permitOffBtn\"><span class=\"spin\"></span><span class=\"label\">Close join</span></button>"
"<button type=\"button\" class=\"btn danger\" id=\"leaveBtn\"><span class=\"spin\"></span><span class=\"label\">Leave network</span></button>"
"</div>"
"<p class=\"hint\" id=\"netMsg\"></p>"
"</div></div>"
"<div id=\"view-devices\" class=\"grid hidden\">"
"<div class=\"card\">"
"<div class=\"card-head\"><h2>Device inventory</h2>"
"<span id=\"devJoinPill\" class=\"pill hidden\">Join open</span></div>"
"<div id=\"devJoinBanner\" class=\"banner join ok hidden\">"
"<div><strong>Permit join open</strong><div class=\"hint\" style=\"margin:0\">"
"Put your Zigbee device in pairing mode within the countdown.</div></div>"
"<div class=\"count\" id=\"devJoinCount\">0s</div></div>"
"<div class=\"toolbar\">"
"<button type=\"button\" class=\"btn secondary\" id=\"refreshDev\"><span class=\"spin\"></span><span class=\"label\">Refresh from NCP</span></button>"
"<button type=\"button\" class=\"btn\" id=\"permitDev\"><span class=\"spin\"></span><span class=\"label\">Permit join 120s</span></button>"
"</div>"
"<div id=\"devList\"></div>"
"<p class=\"hint\">Tap a device for details, rename, interview (ZCL read), and HomeKit exposure.</p>"
"</div></div>"
"<div id=\"view-groups\" class=\"grid hidden\">"
"<div class=\"card\">"
"<div class=\"card-head\"><h2>Grouped devices</h2></div>"
"<p class=\"hint\">Combine Zigbee devices into one HomeKit accessory. Pick a type below — "
"General exposes members as a single light/switch; Thermostat pairs a sensor with a heater switch "
"(±0.5 °C local control).</p>"
"<div id=\"groupList\"></div>"
"<h2 style=\"margin-top:1.25rem\">Create grouped device</h2>"
"<label for=\"grName\">Name</label>"
"<input id=\"grName\" maxlength=\"31\" placeholder=\"Kitchen lights\">"
"<label for=\"grType\">Type</label>"
"<select id=\"grType\">"
"<option value=\"general\">General grouped device</option>"
"<option value=\"thermostat\">Thermostat</option>"
"</select>"
"<div id=\"grGeneral\" class=\"form-block\">"
"<label>Members</label>"
"<div id=\"grMembers\" class=\"member-pick\"></div>"
"<p class=\"hint\">Select any devices to control together as one HomeKit accessory.</p>"
"</div>"
"<div id=\"grThermo\" class=\"form-block hidden\">"
"<label for=\"thSensor\">Temperature sensor</label>"
"<select id=\"thSensor\"></select>"
"<label for=\"thSwitch\">Heater switch</label>"
"<select id=\"thSwitch\"></select>"
"<label for=\"thTarget\">Target temperature (°C)</label>"
"<input id=\"thTarget\" type=\"number\" min=\"10\" max=\"38\" step=\"0.5\" value=\"21\">"
"<label for=\"thMode\">Mode</label>"
"<select id=\"thMode\"><option value=\"heat\">Heat</option><option value=\"off\">Off</option></select>"
"</div>"
"<label class=\"check\"><input type=\"checkbox\" id=\"grHk\" checked> Expose to HomeKit</label>"
"<div class=\"toolbar\">"
"<button type=\"button\" class=\"btn\" id=\"grCreate\"><span class=\"spin\"></span><span class=\"label\">Create group</span></button>"
"</div>"
"<p class=\"hint\" id=\"grMsg\"></p>"
"</div></div>"
"<div id=\"view-sniff\" class=\"grid hidden\">"
"<div class=\"card\">"
"<div class=\"card-head\"><h2>Zigbee sniffer</h2>"
"<span id=\"sniffLive\" class=\"pill\">Live</span></div>"
"<p class=\"hint\">IKEA remotes: after join, <strong>Touchlink a real bulb</strong> (≤5&nbsp;cm until "
"the bulb flashes). The GW joins that group and <strong>removes lights from it</strong> so presses "
"go to HomeKit only (bulb no longer toggles). Holding toward the GW alone will not bind.</p>"
"<div class=\"sniff-toolbar\">"
"<button type=\"button\" class=\"btn secondary sm\" id=\"sniffPause\"><span class=\"label\">Pause</span></button>"
"<button type=\"button\" class=\"btn secondary sm\" id=\"sniffClear\"><span class=\"spin\"></span>"
"<span class=\"label\">Clear</span></button>"
"<label class=\"check\"><input type=\"checkbox\" id=\"sniffRx\" checked> RX</label>"
"<label class=\"check\"><input type=\"checkbox\" id=\"sniffTx\" checked> TX</label>"
"<label class=\"check\"><input type=\"checkbox\" id=\"sniffEvt\" checked> EVT</label>"
"<label class=\"check\"><input type=\"checkbox\" id=\"sniffHideTime\" checked> Hide Time</label>"
"<label class=\"check\"><input type=\"checkbox\" id=\"sniffAutoscroll\" checked> Autoscroll</label>"
"<span class=\"hint\" id=\"sniffCount\" style=\"margin:0\">0 frames</span>"
"</div>"
"<div class=\"sniff-log\" id=\"sniffLog\">Waiting for traffic…</div>"
"</div></div>"
"<div id=\"view-system\" class=\"grid hidden\">"
"<div class=\"card\"><h2>Diagnostics</h2><dl class=\"kv\" id=\"sysKv\"></dl>"
"<button type=\"button\" class=\"btn danger\" id=\"forgetWifi\"><span class=\"spin\"></span><span class=\"label\">Forget home Wi‑Fi</span></button>"
"<p class=\"hint\">Clears STA credentials and re-enables SoftAP setup mode.</p>"
"</div></div>"
"</section>"
"</main>"
"<footer>ICC Gateway</footer>"
"<div id=\"toasts\" aria-live=\"polite\"></div>"
"<div id=\"modalRoot\" class=\"modal-backdrop hidden\" role=\"dialog\" aria-modal=\"true\">"
"<div class=\"modal\">"
"<h3 id=\"mdTitle\">Device</h3>"
"<p class=\"sub\" id=\"mdEui\"></p>"
"<dl class=\"kv\" id=\"mdKv\"></dl>"
"<label for=\"mdName\">Friendly name</label>"
"<input id=\"mdName\" maxlength=\"31\" placeholder=\"Living room sensor\">"
"<div id=\"mdRemoteTypeBox\" class=\"hidden\">"
"<label for=\"mdRemoteType\">Remote type</label>"
"<select id=\"mdRemoteType\">"
"<option value=\"1\">Control a device</option>"
"<option value=\"0\">HomeKit buttons</option>"
"</select>"
"<div id=\"mdTargetBox\" class=\"hidden\">"
"<label for=\"mdTarget\">Target lights / switches / groups</label>"
"<select id=\"mdTarget\" multiple size=\"6\"></select>"
"<p class=\"hint\">Hold Cmd/Ctrl to select several. Groups (e.g. Kitchen light) expand to their "
"members. The gateway keeps all targets in the same on/off state (no native Toggle). After Save, "
"press a button once if the remote group is still unknown.</p>"
"</div>"
"</div>"
"<label class=\"check\" id=\"mdHkRow\"><input type=\"checkbox\" id=\"mdHk\"> Expose to HomeKit</label>"
"<div id=\"mdBtnModes\" class=\"btn-modes hidden\">"
"<h4>Buttons</h4>"
"<p class=\"hint\">Name each button for HomeKit. Stateless = press events; Stateful = On/Off switch "
"(toggle on press; use for automations).</p>"
"<div id=\"mdBtnModeList\"></div>"
"</div>"
"<div id=\"mdBtnTest\" class=\"btn-test hidden\">"
"<h4>Button test</h4>"
"<p class=\"hint\">Press buttons on the physical remote. If Zigbee reaches the gateway, pads light up here "
"(independent of HomeKit).</p>"
"<div class=\"btn-grid\" id=\"mdBtnGrid\"></div>"
"<ul class=\"btn-log\" id=\"mdBtnLog\"><li>Waiting for presses…</li></ul>"
"</div>"
"<div class=\"modal-actions\">"
"<button type=\"button\" class=\"btn\" id=\"mdSave\"><span class=\"spin\"></span><span class=\"label\">Save</span></button>"
"<button type=\"button\" class=\"btn secondary\" id=\"mdInterview\"><span class=\"spin\"></span><span class=\"label\">Read values</span></button>"
"<button type=\"button\" class=\"btn secondary\" id=\"mdClose\"><span class=\"label\">Close</span></button>"
"<button type=\"button\" class=\"btn danger\" id=\"mdRemove\"><span class=\"spin\"></span><span class=\"label\">Remove</span></button>"
"</div>"
"<p class=\"hint\">For temp/humidity sensors: tap <strong>Read values</strong>, then press the sensor button "
"a few times (once/sec) so automatic reporting can be set up while it is awake.</p>"
"</div></div>"
"<script>"
"const $=s=>document.querySelector(s);"
"const $$=s=>[...document.querySelectorAll(s)];"
"let S=null, pollMs=5000, pollTimer=null, selectedEui=null, lastPressSig='';"
"let pendingTargetKeys=[];"
"const BTN_NAMES={5:['Power','Dimmer','Brighter','Left','Right'],4:['On','Off','Left','Right'],"
"2:['On','Off'],1:['Button']};"
"function btnName(n,i){const a=BTN_NAMES[n]||BTN_NAMES[5];return a[i-1]||('Button '+i)}"
"function btnLabel(d,i){const names=d&&d.button_names;if(names&&names[i]&&String(names[i]).trim())return String(names[i]).trim();"
"return btnName(d&&d.buttons||5,i+1)}"
"function controlTargets(){return (S&&S.devices||[]).filter(d=>isLight(d)||isSwitch(d))}"
"function controlGroups(){return ((S&&S.groups)||[]).filter(g=>g&&(g.type==='general'||g.is_light))}"
"function targetKeysFromDevice(d){"
"const keys=[];if(!d)return keys;"
"(d.target_groups||[]).forEach(id=>keys.push('g:'+id));"
"const euis=(d.targets&&d.targets.length)?d.targets:(d.target_eui64?[d.target_eui64]:[]);"
"euis.forEach(e=>{if(e)keys.push('d:'+e)});"
"return keys}"
"function collectTargetSelection(){"
"const sel=$('#mdTarget');if(!sel)return {targets:[],target_groups:[]};"
"const targets=[],target_groups=[];"
"[...sel.selectedOptions].forEach(o=>{const v=o.value||'';"
"if(v.indexOf('g:')===0){const id=Number(v.slice(2));if(id)target_groups.push(id)}"
"else if(v.indexOf('d:')===0)targets.push(v.slice(2));"
"else if(v)targets.push(v)});"
"return {targets,target_groups}}"
"function syncRemoteTypeUi(d,soft){"
"const box=$('#mdRemoteTypeBox'),tgtBox=$('#mdTargetBox'),hkRow=$('#mdHkRow');"
"const typeSel=$('#mdRemoteType'),tgtSel=$('#mdTarget');"
"if(!box||!typeSel)return;"
"if(!d||!isRemote(d)){box.classList.add('hidden');return}"
"box.classList.remove('hidden');"
"const rt=(d.remote_type===1)?1:0;"
"if(!soft){typeSel.value=String(rt);pendingTargetKeys=targetKeysFromDevice(d)}"
"const cur=Number(typeSel.value)||0;"
"const isCtrl=cur===1;"
"if(tgtBox)tgtBox.classList.toggle('hidden',!isCtrl);"
"if(hkRow)hkRow.classList.toggle('hidden',isCtrl);"
"const modesBox=$('#mdBtnModes');if(modesBox)modesBox.classList.toggle('hidden',isCtrl);"
"if(isCtrl&&tgtSel){"
"const devices=controlTargets();"
"const groups=controlGroups();"
"const sig='g:'+groups.map(g=>g.id).join(',')+'|d:'+devices.map(t=>t.eui64).join('|');"
"let want=pendingTargetKeys;"
"if(!want||!want.length){want=soft?[...tgtSel.selectedOptions].map(o=>o.value):targetKeysFromDevice(d)}"
"if(!soft||tgtSel.dataset.sig!==sig){"
"let html='';"
"if(groups.length){html+='<optgroup label=\"Grouped devices\">';"
"groups.forEach(g=>{html+='<option value=\"g:'+g.id+'\">'+(g.name||('Group '+g.id))+"
"' (group, '+((g.members&&g.members.length)||0)+' devices)</option>'});"
"html+='</optgroup>'}"
"html+='<optgroup label=\"Lights and switches\">';"
"devices.forEach(t=>{html+='<option value=\"d:'+t.eui64+'\">'+(t.name||t.model||t.eui64)+"
"' ('+(isLight(t)?'light':'switch')+')</option>'});"
"html+='</optgroup>';"
"tgtSel.innerHTML=html||'<option disabled>No compatible devices</option>';"
"tgtSel.dataset.sig=sig}"
"[...tgtSel.options].forEach(o=>{o.selected=want.indexOf(o.value)>=0});"
"pendingTargetKeys=[...tgtSel.selectedOptions].map(o=>o.value)"
"}"
"}"
"function renderBtnModes(d,soft){"
"const box=$('#mdBtnModes'),list=$('#mdBtnModeList');"
"if(!box||!list)return;"
"const rt=Number(($('#mdRemoteType')||{}).value);"
"const useHk=d&&isRemote(d)&&(rt===0||(rt!==1&&d.remote_type!==1));"
"if(!useHk){box.classList.add('hidden');return}"
"box.classList.remove('hidden');"
"const n=d.buttons||5;"
"const modes=d.button_modes||[];"
"const names=d.button_names||[];"
"if(!soft||list.childElementCount!==n){"
"list.innerHTML='';for(let i=0;i<n;i++){"
"const mode=modes[i]===1?1:0;"
"const nm=(names[i]&&String(names[i]).trim())||btnName(n,i+1);"
"const row=document.createElement('div');row.className='btn-mode-row';"
"row.innerHTML='<label>Button '+(i+1)+'</label>'+"
"'<input type=\"text\" maxlength=\"23\" data-btn-name=\"'+i+'\" value=\"'+nm.replace(/\"/g,'&quot;')+'\">'+"
"'<select data-btn=\"'+i+'\">'+"
"'<option value=\"0\"'+(mode===0?' selected':'')+'>Stateless</option>'+"
"'<option value=\"1\"'+(mode===1?' selected':'')+'>Stateful switch</option></select>';"
"list.appendChild(row)}}"
"else{$$('#mdBtnModeList input[data-btn-name]').forEach(inp=>{"
"const i=Number(inp.dataset.btnName);if(names[i]!=null&&document.activeElement!==inp)"
"inp.value=String(names[i])||btnName(n,i+1)})}"
"}"
"function collectBtnModes(){"
"return $$('#mdBtnModeList select').map(s=>Number(s.value)||0)}"
"function collectBtnNames(){"
"return $$('#mdBtnModeList input[data-btn-name]').map(inp=>(inp.value||'').trim())}"
"function fmtAge(ms){if(ms<1000)return 'just now';if(ms<60000)return Math.round(ms/1000)+'s ago';"
"return Math.round(ms/60000)+'m ago'}"
"function renderBtnTest(d){"
"const box=$('#mdBtnTest'),grid=$('#mdBtnGrid'),log=$('#mdBtnLog');"
"if(!box||!grid||!log)return;"
"if(!d||!isRemote(d)){box.classList.add('hidden');return}"
"box.classList.remove('hidden');"
"const n=d.buttons||5;"
"if(grid.childElementCount!==n){grid.innerHTML='';for(let i=1;i<=n;i++){"
"const b=document.createElement('div');b.className='btn-pad';b.dataset.btn=i;"
"b.textContent=btnLabel(d,i-1);grid.appendChild(b)}}"
"const mine=(S.remote_presses||[]).filter(p=>p.eui64===d.eui64);"
"$$('#mdBtnGrid .btn-pad').forEach(el=>{"
"const hit=mine.find(p=>p.button===Number(el.dataset.btn)&&p.age_ms<2500);"
"el.classList.toggle('on',!!hit)});"
"if(!mine.length){log.innerHTML='<li>Waiting for presses…</li>';return}"
"log.innerHTML=mine.slice(0,8).map(p=>'<li>Button '+p.button+' · '+btnLabel(d,p.button-1)+' · '+p.event+"
"' · '+fmtAge(p.age_ms)+'</li>').join('');"
"const sig=mine.map(p=>p.button+p.event+p.age_ms).join('|');"
"if(sig!==lastPressSig&&mine[0]&&mine[0].age_ms<2000){"
"lastPressSig=sig}"
"}"
"function pill(el,text,cls){if(!el)return;el.className='pill '+(cls||'');el.textContent=text}"
"function kv(el,rows){el.innerHTML=rows.map(([k,v])=>`<dt>${k}</dt><dd>${(v!=null&&v!=='')?v:'—'}</dd>`).join('')}"
"function toast(msg,kind){const t=document.createElement('div');t.className='toast '+(kind||'ok');"
"t.innerHTML=`<span class=\"dot\"></span><div>${msg}</div>`;$('#toasts').appendChild(t);"
"setTimeout(()=>{t.style.opacity='0';t.style.transition='opacity .25s';setTimeout(()=>t.remove(),260)},3200)}"
"function setBusy(btn,on,label){if(!btn)return;btn.disabled=!!on;btn.classList.toggle('busy',!!on);"
"const lab=btn.querySelector('.label');if(lab&&label)lab.textContent=label}"
"async function api(path,opt){const r=await fetch(path,opt);const ct=r.headers.get('content-type')||'';"
"const body=ct.includes('json')?await r.json():await r.text();"
"if(!r.ok){const err=(body&&body.error)||(typeof body==='string'?body:r.statusText);throw new Error(err||'Request failed')}"
"if(body&&body.ok===false)throw new Error(body.error||'Request failed');return body}"
"function isSetup(s){return s.wifi==='ap_setup'||s.wifi==='failed'||!s.has_sta}"
"let sniffTimer=null,sniffPaused=false,sniffSeq=-1,sniffActive=false;"
"const CLUSTER_NAME={0x0000:'Basic',0x0001:'PowerCfg',0x0003:'Identify',0x0004:'Groups',0x0005:'Scenes',0x0006:'OnOff',0x0008:'Level',"
"0x000A:'Time',0x0020:'PollCtrl',0x0021:'Bind',0x8021:'BindRsp',0x0033:'MgmtBind',0x8033:'MgmtBindRsp',"
"0x0013:'DeviceAnnce',0xFC7F:'IkeaBtn',0x0402:'Temp',0x0405:'Humidity',0x0019:'StackStatus',0x0080:'Poll',"
"0x001F:'Zdo0x1f',0x8004:'SimpleDescRsp',0x8005:'ActiveEpRsp',0x8033:'MgmtBindRsp',0x0022:'Unbind',"
"0x8022:'UnbindRsp'};"
"function clusterLabel(c){return (CLUSTER_NAME[c]||'')?(CLUSTER_NAME[c]+' 0x'+c.toString(16).padStart(4,'0'))"
":('0x'+Number(c).toString(16).padStart(4,'0'))}"
"function msgTypeLabel(dir,t){"
"if(dir==='EVT')return t===0xFF?'':' sent';"
"const m={0:'UNICAST',1:'UNICAST_REPLY',2:'MULTICAST',3:'MULTICAST_LOOP',4:'BROADCAST',5:'BROADCAST_LOOP'};"
"return m[t]||('type='+t)}"
"function esc(s){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]))}"
"function renderSniff(entries){"
"const showRx=$('#sniffRx').checked,showTx=$('#sniffTx').checked,showEvt=$('#sniffEvt').checked;"
"const hideTime=$('#sniffHideTime')&&$('#sniffHideTime').checked;"
"const filtered=entries.filter(e=>{"
"if(hideTime&&e.cluster===0x000A)return false;"
"return (e.dir==='RX'&&showRx)||(e.dir==='TX'&&showTx)||(e.dir==='EVT'&&showEvt)});"
"$('#sniffCount').textContent=filtered.length+' / '+entries.length+' frames';"
"if(!filtered.length){$('#sniffLog').textContent='No frames yet.';return}"
"const el=$('#sniffLog');const stick=el.scrollHeight-el.scrollTop-el.clientHeight<40;"
"el.innerHTML=filtered.map(e=>{"
"const cls=e.dir.toLowerCase();"
"const t=(e.t/1000).toFixed(3)+'s';"
"let line='<span class=\"'+cls+'\">'+e.dir+'</span> <span class=\"meta\">'+t+'</span> ';"
"line+='node=0x'+Number(e.node).toString(16).padStart(4,'0');"
"line+=' '+clusterLabel(e.cluster);"
"const mt=msgTypeLabel(e.dir,e.type);if(mt)line+=' '+mt;"
"if(e.group)line+=' grp='+e.group;"
"line+=' ep='+e.src_ep+'→'+e.dst_ep;"
"if(e.dir==='RX')line+=' rssi='+e.rssi;"
"if(e.dir!=='RX'||e.status)line+=' st=0x'+Number(e.status).toString(16).padStart(2,'0');"
"if(e.hex)line+='\\n  '+esc(e.hex);"
"return line}).join('\\n');"
"if($('#sniffAutoscroll').checked&&stick)el.scrollTop=el.scrollHeight}"
"async function pollSniff(){"
"if(!sniffActive||sniffPaused)return;"
"try{const j=await api('/api/zigbee/sniff');"
"if(j.seq!==sniffSeq){sniffSeq=j.seq;renderSniff(j.entries||[])}"
"}catch(e){}}"
"function startSniff(){sniffActive=true;$('#sniffLive').classList.add('on');"
"if(!sniffTimer)sniffTimer=setInterval(pollSniff,400);pollSniff()}"
"function stopSniff(){sniffActive=false;$('#sniffLive').classList.remove('on');"
"if(sniffTimer){clearInterval(sniffTimer);sniffTimer=null}}"
"function showTab(name){$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));"
"['overview','network','devices','groups','sniff','system'].forEach(t=>$('#view-'+t).classList.toggle('hidden',t!==name));"
"if(name==='sniff')startSniff();else stopSniff()}"
"function fmtPan(id){return id!=null?('0x'+Number(id).toString(16).padStart(4,'0')):'—'}"
"function findDev(eui){return (S&&S.devices||[]).find(d=>d.eui64===eui)}"
"function isRemote(d){return d&&(d.kind==='remote'||(d.model&&/remote|shortcut|styrbar|symfonisk|wireless switch|E1810|E1743|E1766|E2001|E2002|Remote Control N2/i.test(d.model))||"
"(d.name&&/remote|shortcut|styrbar/i.test(d.name)))}"
"function isLight(d){return d&&!isRemote(d)&&(d.kind==='light'||d.has_level||"
"(d.model&&/TRADFRI|Driver|ICPSHC|LED|bulb|DIM|GU10|E27|E14/i.test(d.model)&&!/remote/i.test(d.model||''))||"
"(d.manufacturer&&/IKEA/i.test(d.manufacturer)&&d.has_onoff&&!isSwitchName(d)&&!isRemote(d)))}"
"function isSwitchName(d){return d&&(d.model&&/SWP|SWITCH|PLUG|RELAY|OUTLET|ZBMINI|S31|BASICZBR3/i.test(d.model))&&!isRemote(d)}"
"function isSwitch(d){return d&&!isLight(d)&&!isRemote(d)&&(d.kind==='switch'||d.has_onoff||isSwitchName(d))}"
"function deviceKind(d){"
"if(isRemote(d)){const n=d.buttons||0;return n?('Remote · '+n+' buttons'):'Remote control'}"
"if(isLight(d))return 'Light / dimmer';"
"if(isSwitch(d))return 'Smart switch';"
"if(d.has_temp&&d.has_humidity)return 'Temperature & humidity sensor';"
"if(d.has_temp)return 'Temperature sensor';"
"if(d.has_humidity)return 'Humidity sensor';"
"if(d.model&&/SNZB-02|TH|temp|humid/i.test(d.model))return 'Temperature & humidity sensor';"
"if(d.has_battery)return 'Battery sensor';"
"const t=(d.type||'').replace(/_/g,' ');"
"return t?t.charAt(0).toUpperCase()+t.slice(1):'Zigbee device'}"
"function syncGroupForm(){"
"const t=$('#grType').value;"
"$('#grGeneral').classList.toggle('hidden',t!=='general');"
"$('#grThermo').classList.toggle('hidden',t!=='thermostat')}"
"function signalLevel(d){"
"const r=d.rssi,l=d.lqi;"
"if((r==null||r===0)&&(l==null||l===0))return 0;"
"if(r!=null&&r!==0){if(r>=-50)return 4;if(r>=-65)return 3;if(r>=-78)return 2;if(r>=-90)return 1;return 1}"
"if(l>=200)return 4;if(l>=150)return 3;if(l>=100)return 2;if(l>=50)return 1;return 1}"
"function signalHtml(d){"
"const lvl=signalLevel(d);"
"const parts=[];"
"if(d.rssi!=null&&d.rssi!==0)parts.push(d.rssi+' dBm');"
"if(d.lqi)parts.push('LQI '+d.lqi);"
"const tip=parts.length?parts.join(' · '):(lvl?'Signal':'No signal yet');"
"const cls='sig'+(lvl===0?' none':(lvl===1?' weak':''));"
"return '<span class=\"sig-wrap\" title=\"'+tip+'\"><span class=\"'+cls+'\" data-lvl=\"'+lvl+'\""
" aria-label=\"Zigbee signal '+lvl+' of 4\"><i></i><i></i><i></i><i></i></span></span>'}"
"function schedulePoll(){const remoteOpen=selectedEui&&isRemote(findDev(selectedEui));"
"const next=remoteOpen?600:((S&&S.permit_join>0)?1000:5000);"
"if(next!==pollMs){pollMs=next;clearInterval(pollTimer);pollTimer=setInterval(refresh,pollMs)}}"
"function openModal(eui,soft){const d=findDev(eui);if(!d)return;"
"const already=selectedEui===eui&&!$('#modalRoot').classList.contains('hidden');"
"selectedEui=eui;"
"$('#modalRoot').classList.remove('hidden');"
"$('#mdTitle').textContent=d.name||d.model||d.label||'Device';"
"$('#mdEui').textContent=d.eui64;"
"if(!soft&&!already){$('#mdName').value=d.name||'';$('#mdHk').checked=!!d.homekit_expose}"
"kv($('#mdKv'),["
"['Device type',deviceKind(d)],['Node type',d.type],['Short addr',fmtPan(d.node_id)],"
"['Manufacturer',d.manufacturer],"
"['Model',d.model],['Firmware',d.firmware],"
"].concat(isLight(d)?["
"['Power',d.has_onoff?(d.onoff_on?'On':'Off'):'—'],"
"['Brightness',(d.has_level?d.brightness:(d.onoff_on?100:0))+' %']"
"]:isRemote(d)?["
"['Buttons',d.buttons||'—'],"
"['Battery',d.has_battery?(d.battery_pct+' %'):null]"
"]:isSwitch(d)?["
"['Power',d.has_onoff?(d.onoff_on?'On':'Off'):'—']"
"]:["
"['Temperature',d.has_temp?(d.temperature_c.toFixed(1)+' °C'):null],"
"['Humidity',d.has_humidity?(d.humidity_pct.toFixed(1)+' %'):null],"
"['Battery',d.has_battery?(d.battery_pct+' %'):null]"
"]).concat(["
"['Zigbee signal',(d.rssi!=null&&d.rssi!==0)||d.lqi?((d.rssi!=null&&d.rssi!==0?d.rssi+' dBm':'—')+' / LQI '+(d.lqi||'—')):null],"
"['HomeKit',d.homekit_expose?'exposed':'not exposed']]));"
"syncRemoteTypeUi(d,soft||already);renderBtnModes(d,soft||already);renderBtnTest(d);schedulePoll()}"
"function closeModal(){$('#modalRoot').classList.add('hidden');selectedEui=null;pendingTargetKeys=[];"
"$('#mdBtnTest').classList.add('hidden');$('#mdBtnModes').classList.add('hidden');"
"$('#mdRemoteTypeBox').classList.add('hidden');schedulePoll()}"
"function renderModal(){if(selectedEui&&findDev(selectedEui))openModal(selectedEui,true)}"
"function render(){if(!S)return;"
"const setup=isSetup(S);$('#setup').classList.toggle('hidden',!setup);$('#app').classList.toggle('hidden',setup);"
"$('#tabs').classList.toggle('hidden',setup);"
"if(S.icc==='CONNECTED')pill($('#topPill'),'ICC online','ok');"
"else if(setup)pill($('#topPill'),'Wi‑Fi setup','warn');"
"else pill($('#topPill'),'ICC offline','bad');"
"$('#mIcc').textContent=S.icc||'—';"
"$('#mIccSub').textContent=`ASH ${S.ash||'—'} · EZSP ${S.ezsp!=null?S.ezsp:'—'} · ${S.ember||''}`;"
"$('#mNet').textContent=S.network||'—';"
"$('#mNetSub').textContent=S.net_valid?`ch ${S.channel} · PAN ${fmtPan(S.pan_id)}`:'not formed';"
"$('#mDev').textContent=String(S.device_count||0);"
"$('#mWifiIp').textContent=S.ip&&S.ip!=='-'?S.ip:(S.ap_active?S.ap_ip:'—');"
"$('#mWifiSub').textContent=S.ssid?S.ssid:(S.ap_active?('SoftAP '+S.ap_ssid):'—');"
"kv($('#overviewKv'),["
"['EUI64',S.eui64],['EmberZNet',S.ember],['Node type',S.node_type],['EPID',S.epid],"
"['Uptime',S.uptime],['RSSI',S.rssi!=null?(S.rssi+' dBm'):'—']]);"
"const hk=S.homekit||{};"
"kv($('#hkKv'),["
"['Status',hk.status||(hk.started?'running':'off')],"
"['Setup code',hk.setup_code],['Setup ID',hk.setup_id],"
"['Paired',hk.paired?'yes':'no'],['Accessories',hk.accessories]]);"
"const joined=S.network==='JOINED';"
"const pj=S.permit_join||0;"
"$('#netBanner').className='banner '+(joined?(pj?'ok':'ok'):'warn');"
"$('#netBanner').textContent=joined?(pj?`Coordinator online · permit join open · ${pj}s left`:"
"'Coordinator online · join window closed'):"
"'No Zigbee network yet — create one to start pairing devices.';"
"kv($('#netKv'),["
"['State',S.network],['Channel',S.channel],['PAN ID',fmtPan(S.pan_id)],"
"['Extended PAN',S.epid],['TX power',S.tx_power!=null?(S.tx_power+' dBm'):null],"
"['Permit join', pj? (pj+' s open'):'closed']]);"
"$('#formBox').classList.toggle('hidden',joined);"
"$('#netActions').classList.toggle('hidden',!joined);"
"const joinOpen=pj>0;"
"$('#devJoinBanner').classList.toggle('hidden',!joinOpen);"
"$('#devJoinPill').classList.toggle('hidden',!joinOpen);"
"if(joinOpen){$('#devJoinCount').textContent=pj+'s';pill($('#devJoinPill'),'Join open '+pj+'s','ok')}"
"const list=$('#devList');"
"if(!S.devices||!S.devices.length){list.innerHTML='<div class=\"empty\"><strong>No devices yet</strong>"
"Open permit join, then pair a Zigbee device with this gateway.</div>';}"
"else{list.innerHTML=S.devices.map(d=>{const title=d.name||d.model||d.label||d.eui64;"
"const chips=[];"
"if(isRemote(d))chips.push('<span class=\"chip\">'+(d.buttons?d.buttons+' btn':'Remote')+'</span>');"
"else if(isLight(d))chips.push('<span class=\"chip\">'+(d.has_level?(d.brightness+'%'):(d.has_onoff?(d.onoff_on?'On':'Off'):'Light'))+'</span>');"
"else if(isSwitch(d))chips.push('<span class=\"chip\">'+(d.has_onoff?(d.onoff_on?'On':'Off'):'Switch')+'</span>');"
"if(d.has_temp)chips.push('<span class=\"chip\">'+d.temperature_c.toFixed(1)+'°C</span>');"
"if(d.has_humidity)chips.push('<span class=\"chip\">'+d.humidity_pct.toFixed(0)+'%</span>');"
"if(d.has_battery)chips.push('<span class=\"chip\">bat '+d.battery_pct+'%</span>');"
"if(d.homekit_expose)chips.push('<span class=\"chip\">HomeKit</span>');"
"let html='<div class=\"device\" data-eui=\"'+d.eui64+'\"><div>';"
"html+='<div class=\"title\">'+title+signalHtml(d)+'</div>';"
"html+='<div class=\"id\">'+d.eui64+'</div>';"
"html+='<div class=\"kind\">'+deviceKind(d)+'</div>';"
"html+='<div class=\"meta\">'+(d.model||'')+(d.model?' · ':'')+fmtPan(d.node_id)+'</div>';"
"if(chips.length)html+='<div class=\"vals\">'+chips.join('')+'</div>';"
"html+='</div><span class=\"pill ok\">Details</span></div>';return html}).join('')}"
"const sensors=(S.devices||[]).filter(d=>d.has_temp||(d.model&&/SNZB-02|TH|temp|humid/i.test(d.model)));"
"const switches=(S.devices||[]).filter(d=>isSwitch(d));"
"const fillSel=(sel,list,cur)=>{const v=cur||sel.value;sel.innerHTML=list.map(d=>"
"'<option value=\"'+d.eui64+'\">'+(d.name||d.model||d.eui64)+'</option>').join('')||"
"'<option value=\"\">— none available —</option>';if(v)sel.value=v};"
"fillSel($('#thSensor'),sensors);fillSel($('#thSwitch'),switches);"
"const mp=$('#grMembers');"
"const prev=new Set([...mp.querySelectorAll('input[type=checkbox]:checked')].map(c=>c.value));"
"mp.innerHTML=(S.devices||[]).length?S.devices.map(d=>{"
"const lab=d.name||d.model||d.eui64;"
"const ck=prev.has(d.eui64)?' checked':'';"
"return '<label class=\"check\"><input type=\"checkbox\" value=\"'+d.eui64+'\"'+ck+'> '+lab+'</label>'}).join('')"
":'<div class=\"empty\" style=\"padding:.5rem 0\">No devices yet</div>';"
"const gl=$('#groupList');"
"const groups=S.groups||[];"
"if(!groups.length){gl.innerHTML='<div class=\"empty\"><strong>No grouped devices yet</strong>"
"Create one below — pick General or Thermostat.</div>';}"
"else{gl.innerHTML=groups.map(g=>{"
"const chips=[];"
"if(g.type==='thermostat'){"
"const cur=g.has_current_temp?(g.current_temp_c.toFixed(1)+' °C'):'—';"
"const st=g.mode==='off'?'Off':(g.heating?'Heating':'Idle');"
"chips.push('<span class=\"chip\">'+cur+'</span>');"
"chips.push('<span class=\"chip\">tgt '+Number(g.target_c).toFixed(1)+'°C</span>');"
"chips.push('<span class=\"chip\">'+st+'</span>');"
"}else{"
"chips.push('<span class=\"chip\">'+(g.is_light?'Light':'Switch')+'</span>');"
"chips.push('<span class=\"chip\">'+(g.on?'On':'Off')+'</span>');"
"if(g.is_light)chips.push('<span class=\"chip\">'+g.brightness+'%</span>');"
"chips.push('<span class=\"chip\">'+(g.members||[]).length+' members</span>');"
"}"
"if(g.homekit_expose)chips.push('<span class=\"chip\">HomeKit</span>');"
"let html='<div class=\"device\" data-gid=\"'+g.id+'\"><div style=\"min-width:0;flex:1\">';"
"html+='<div class=\"title\">'+g.name+'</div>';"
"if(g.type==='thermostat'){"
"html+='<div class=\"kind\">Thermostat · sensor '+(g.sensor_eui||'').slice(-8)+' · switch '+(g.switch_eui||'').slice(-8)+'</div>';"
"}else{"
"html+='<div class=\"kind\">General group · '+((g.members||[]).map(e=>e.slice(-8)).join(', ')||'no members')+'</div>';"
"}"
"html+='<div class=\"vals\">'+chips.join('')+'</div></div>';"
"html+='<button type=\"button\" class=\"btn danger sm gr-del\" data-gid=\"'+g.id+'\">"
"<span class=\"label\">Remove</span></button></div>';"
"return html}).join('')}"
"kv($('#sysKv'),["
"['Wi‑Fi mode',S.wifi],['Home SSID',S.ssid],['Home IP',S.ip],['SoftAP',S.ap_active?(S.ap_ssid+' @ '+S.ap_ip):'off'],"
"['HomeKit',(hk.setup_code||'—')+(hk.paired?' · paired':' · unpaired')],"
"['TX / RX',(S.tx||0)+' / '+(S.rx||0)],['ASH OK / bad',(S.ash_ok||0)+' / '+(S.ash_bad||0)],"
"['CRC / timeouts',(S.crc_err||0)+' / '+(S.timeouts||0)],['EZSP cmd / rsp',(S.ezsp_cmd||0)+' / '+(S.ezsp_rsp||0)],"
"['Last error',S.last_error||'—']]);"
"renderModal();schedulePoll()}"
"async function refresh(){try{S=await api('/api/status');render()}catch(e){console.log(e)}}"
"async function withBtn(btn,busyLabel,doneLabel,fn,okMsg){"
"setBusy(btn,true,busyLabel);try{await fn();if(okMsg)toast(okMsg,'ok')}catch(e){toast(e.message||String(e),'err');throw e}"
"finally{setBusy(btn,false,doneLabel)}}"
"$('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(b)showTab(b.dataset.tab)});"
"$('#sniffPause').onclick=()=>{sniffPaused=!sniffPaused;$('#sniffPause').querySelector('.label').textContent=sniffPaused?'Resume':'Pause';"
"$('#sniffLive').textContent=sniffPaused?'Paused':'Live';if(!sniffPaused)pollSniff()};"
"$('#sniffClear').onclick=async()=>{await withBtn($('#sniffClear'),'…','Clear',async()=>{"
"await api('/api/zigbee/sniff/clear',{method:'POST'});sniffSeq=-1;await pollSniff()})};"
"['sniffRx','sniffTx','sniffEvt','sniffHideTime'].forEach(id=>{const el=$('#'+id);if(el)el.onchange=()=>pollSniff()});"
"$('#devList').addEventListener('click',e=>{const row=e.target.closest('.device[data-eui]');if(row)openModal(row.dataset.eui)});"
"$('#mdClose').onclick=closeModal;"
"$('#modalRoot').addEventListener('click',e=>{if(e.target===$('#modalRoot'))closeModal()});"
"$('#mdSave').onclick=async()=>{if(!selectedEui)return;"
"await withBtn($('#mdSave'),'Saving…','Save',async()=>{"
"const savedName=$('#mdName').value.trim();"
"const payload={eui64:selectedEui,name:savedName,homekit_expose:$('#mdHk').checked};"
"const d=findDev(selectedEui);if(isRemote(d)){"
"payload.remote_type=Number($('#mdRemoteType').value)||0;"
"if(payload.remote_type===1){"
"const sel=collectTargetSelection();"
"payload.targets=sel.targets;payload.target_groups=sel.target_groups;payload.homekit_expose=false}"
"else{payload.button_modes=collectBtnModes();payload.button_names=collectBtnNames()}"
"}"
"await api('/api/zigbee/devices/update',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(payload)});"
"/* Optimistic local update so soft polls cannot flash the old name. */"
"if(d){d.name=savedName;d.homekit_expose=!!$('#mdHk').checked;"
"if(payload.button_modes)d.button_modes=payload.button_modes.slice();"
"if(payload.button_names)d.button_names=payload.button_names.slice();"
"if(payload.remote_type!=null)d.remote_type=payload.remote_type}"
"$('#mdName').value=savedName;$('#mdTitle').textContent=savedName||(d&&(d.model||d.label))||'Device';"
"await refresh();"
"const d2=findDev(selectedEui);"
"if(d2){$('#mdName').value=(d2.name!=null&&d2.name!=='')?d2.name:savedName;"
"$('#mdTitle').textContent=d2.name||d2.model||d2.label||'Device';"
"$('#mdHk').checked=!!d2.homekit_expose;renderBtnModes(d2,false)}"
"else{$('#mdName').value=savedName}"
"},'Device saved')};"
"$('#mdRemoteType').onchange=()=>{const d=findDev(selectedEui);syncRemoteTypeUi(d,true);renderBtnModes(d,true)};"
"const mdTargetEl=$('#mdTarget');"
"if(mdTargetEl)mdTargetEl.onchange=()=>{pendingTargetKeys=[...mdTargetEl.selectedOptions].map(o=>o.value)};"
"$('#mdInterview').onclick=async()=>{if(!selectedEui)return;"
"await withBtn($('#mdInterview'),'Reading…','Read values',async()=>{"
"await api('/api/zigbee/devices/interview',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({eui64:selectedEui})});"
"await new Promise(r=>setTimeout(r,800));await refresh()},"
"'Done — wake sleepy devices (button) if values did not update')};"
"$('#mdRemove').onclick=async()=>{if(!selectedEui||!confirm('Remove this device from inventory?'))return;"
"await withBtn($('#mdRemove'),'Removing…','Remove',async()=>{"
"await api('/api/zigbee/devices/remove',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({eui64:selectedEui})});closeModal();await refresh()},'Device removed')};"
"$('#grType').addEventListener('change',syncGroupForm);syncGroupForm();"
"$('#grCreate').onclick=async()=>{"
"const name=$('#grName').value.trim(),type=$('#grType').value,hk=$('#grHk').checked;"
"if(!name){toast('Name required','warn');return}"
"if(type==='thermostat'){"
"const sensor=$('#thSensor').value,sw=$('#thSwitch').value;"
"const target=parseFloat($('#thTarget').value)||21;"
"if(!sensor||!sw){toast('Sensor and switch required','warn');return}"
"if(sensor===sw){toast('Sensor and switch must be different devices','warn');return}"
"await withBtn($('#grCreate'),'Creating…','Create group',async()=>{"
"await api('/api/groups/create',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({name,type:'thermostat',sensor_eui:sensor,switch_eui:sw,target_c:target,"
"mode:$('#thMode').value,homekit_expose:hk})});"
"$('#grName').value='';await refresh()},'Thermostat group created')}"
"else{"
"const members=[...$$('#grMembers input[type=checkbox]:checked')].map(c=>c.value);"
"if(!members.length){toast('Pick at least one member device','warn');return}"
"await withBtn($('#grCreate'),'Creating…','Create group',async()=>{"
"await api('/api/groups/create',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({name,type:'general',members,homekit_expose:hk})});"
"$('#grName').value='';$$('#grMembers input[type=checkbox]').forEach(c=>c.checked=false);"
"await refresh()},'Grouped device created')}"
"};"
"$('#groupList').addEventListener('click',async e=>{"
"const btn=e.target.closest('.gr-del[data-gid]');if(!btn)return;"
"const id=+btn.dataset.gid;if(!id||!confirm('Remove this grouped device?'))return;"
"await withBtn(btn,'…','Remove',async()=>{"
"await api('/api/groups/remove',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({id})});await refresh()},'Group removed')});"
"$('#scan').addEventListener('change',()=>{if($('#scan').value)$('#ssid').value=$('#scan').value});"
"$('#showPass').addEventListener('change',()=>{$('#password').type=$('#showPass').checked?'text':'password'});"
"$('#scanBtn').onclick=async()=>{"
"const btn=$('#scanBtn'),bar=$('#scanBar'),st=$('#scanStatus');"
"setBusy(btn,true,'Scanning…');bar.style.width='15%';st.textContent='Searching nearby networks…';"
"try{const t=setInterval(()=>{const w=parseFloat(bar.style.width)||10;bar.style.width=Math.min(90,w+8)+'%'},200);"
"const j=await api('/api/wifi/scan');clearInterval(t);bar.style.width='100%';"
"const sel=$('#scan');sel.innerHTML='<option value=\"\">— select a network —</option>';"
"(j.ssids||[]).forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o)});"
"const n=(j.ssids&&j.ssids.length)||0;st.textContent=n?(n+' networks found'):'No networks — type SSID manually';"
"toast(n?(n+' networks found'):'No networks found',n?'ok':'warn')}"
"catch(e){st.textContent='Scan failed — reconnect to SoftAP and retry';bar.style.width='0';toast(e.message,'err')}"
"setBusy(btn,false,'Scan');setTimeout(()=>bar.style.width='0',600)};"
"$('#saveWifi').onclick=async()=>{"
"const ssid=$('#ssid').value.trim();if(!ssid){toast('SSID required','warn');return}"
"await withBtn($('#saveWifi'),'Connecting…','Save & connect',async()=>{"
"$('#wifiMsg').textContent='Connecting… SoftAP turns off when home Wi‑Fi succeeds.';"
"await api('/wifi/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:`ssid=${encodeURIComponent(ssid)}&password=${encodeURIComponent($('#password').value)}`});"
"$('#wifiMsg').textContent='Saved. Join your home Wi‑Fi and open the gateway IP from your router.';"
"setTimeout(refresh,2500)},'Credentials saved')};"
"$('#formBtn').onclick=async()=>{"
"await withBtn($('#formBtn'),'Forming…','Create Zigbee network',async()=>{"
"$('#netMsg').textContent='Forming network…';"
"await api('/api/zigbee/form',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({channel:+$('#ch').value,tx_power:+$('#tx').value})});"
"$('#netMsg').textContent='Network created';await refresh()},'Zigbee network created')};"
"$('#leaveBtn').onclick=async()=>{if(!confirm('Leave Zigbee network?'))return;"
"await withBtn($('#leaveBtn'),'Leaving…','Leave network',async()=>{"
"await api('/api/zigbee/leave',{method:'POST'});await refresh()},'Left Zigbee network')};"
"async function permit(sec,btn){"
"const open=sec>0;const base=(btn.querySelector('.label')&&btn.querySelector('.label').dataset.base)||'Done';"
"await withBtn(btn,open?'Opening…':'Closing…',base,async()=>{"
"await api('/api/zigbee/permit',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({duration:sec})});await refresh()},open?('Permit join open for '+sec+'s'):'Join window closed')}"
"$$('#permitBtn,#permitDev,#permitOffBtn,#refreshDev,#formBtn,#leaveBtn,#forgetWifi,#scanBtn,#saveWifi,#mdSave,#mdInterview,#mdRemove').forEach(b=>{"
"const lab=b.querySelector('.label');if(lab)lab.dataset.base=lab.textContent});"
"$('#permitBtn').onclick=()=>permit(120,$('#permitBtn'));"
"$('#permitOffBtn').onclick=()=>permit(0,$('#permitOffBtn'));"
"$('#permitDev').onclick=()=>permit(120,$('#permitDev'));"
"$('#refreshDev').onclick=async()=>{"
"await withBtn($('#refreshDev'),'Refreshing…','Refresh from NCP',async()=>{"
"await api('/api/zigbee/devices/refresh',{method:'POST'});await refresh();"
"const n=(S&&S.device_count)||0;toast(n?(n+' device'+(n===1?'':'s')+' reported'):'No devices on NCP yet',n?'ok':'warn')})};"
"$('#forgetWifi').onclick=async()=>{if(!confirm('Forget home Wi‑Fi and enable SoftAP setup?'))return;"
"await withBtn($('#forgetWifi'),'Forgetting…','Forget home Wi‑Fi',async()=>{"
"await api('/wifi/clear',{method:'POST'});toast('SoftAP setup restored','ok');location.reload()})};"
"refresh();pollTimer=setInterval(refresh,pollMs);"
"</script></body></html>";
