#pragma once

/* Compact SoftAP-only setup UI (~4 KiB). Full WEB_APP_HTML is too large for C3 SoftAP TX. */

static const char WEB_SETUP_HTML[] =
"<!DOCTYPE html><html lang=en><head>"
"<meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>ICC Gateway · Wi‑Fi setup</title>"
"<style>"
":root{--bg:#0a101c;--panel:#121a2b;--line:#243049;--text:#e8eef8;--muted:#8b9bb4;--accent:#1ec8a5}"
"*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);"
"min-height:100vh;padding:1.25rem}"
".wrap{max-width:420px;margin:0 auto}"
"h1{font-size:1.15rem;margin:0 0 .25rem}p.lead{color:var(--muted);font-size:.85rem;margin:0 0 1.1rem;line-height:1.4}"
".card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:1rem 1.05rem}"
"label{display:block;color:var(--muted);font-size:.76rem;margin:.65rem 0 .25rem;font-weight:600}"
"input,select{width:100%;padding:.68rem .75rem;border-radius:9px;border:1px solid var(--line);"
"background:#0d1524;color:var(--text);font-size:.92rem}"
".row{display:flex;gap:.5rem;align-items:stretch}.row select{flex:1}"
"button{appearance:none;border:0;border-radius:9px;padding:.68rem .9rem;font-weight:650;font-size:.88rem;"
"cursor:pointer;background:linear-gradient(135deg,var(--accent),#149e90);color:#041512}"
"button.sec{background:#161f32;color:var(--text);border:1px solid var(--line)}"
"button:disabled{opacity:.45}"
".hint{color:var(--muted);font-size:.78rem;margin:.55rem 0 0;line-height:1.4}"
".msg{min-height:1.2rem;margin:.75rem 0 0;font-size:.84rem;color:var(--muted)}"
".msg.ok{color:#baf7e8}.msg.err{color:#ffb4b4}"
"</style></head><body><div class=wrap>"
"<h1>ICC Gateway</h1>"
"<p class=lead>SoftAP setup — join home Wi‑Fi. On a mesh, pick the strongest AP (highest dBm).</p>"
"<div class=card>"
"<label>Nearby access points</label>"
"<div class=row><select id=scan><option value=\"\">— Scan to discover —</option></select>"
"<button type=button class=sec id=scanBtn>Scan</button></div>"
"<p class=hint id=scanStatus>Scan listens for nearby APs (a few seconds). You can also type SSID/BSSID.</p>"
"<label for=ssid>SSID</label><input id=ssid maxlength=32 autocomplete=off autocapitalize=none>"
"<label for=bssid>BSSID (optional)</label>"
"<input id=bssid maxlength=17 autocomplete=off autocapitalize=none placeholder=\"aa:bb:cc:dd:ee:ff\">"
"<label for=password>Password</label>"
"<input id=password type=password maxlength=63>"
"<label class=hint style=\"display:flex;gap:.4rem;align-items:center;margin-top:.55rem\">"
"<input type=checkbox id=showPass style=\"width:auto\"> Show password</label>"
"<button type=button id=save style=\"width:100%;margin-top:.9rem\">Save &amp; connect</button>"
"<p class=msg id=msg></p>"
"</div></div>"
"<script>"
"const $=s=>document.querySelector(s);"
"async function api(u,opt){const r=await fetch(u,opt);const t=await r.text();"
"let j;try{j=JSON.parse(t)}catch(e){throw new Error(t||r.status)}if(!r.ok)throw new Error(j.error||t);return j}"
"$('#showPass').onchange=()=>{$('#password').type=$('#showPass').checked?'text':'password'};"
"$('#scan').onchange=()=>{const v=$('#scan').value;if(!v)return;"
"try{const a=JSON.parse(v);$('#ssid').value=a.ssid||'';$('#bssid').value=a.bssid||''}catch(e){}};"
"$('#scanBtn').onclick=async()=>{const btn=$('#scanBtn'),st=$('#scanStatus'),msg=$('#msg');"
"btn.disabled=true;st.textContent='Scanning…';msg.textContent='';"
"try{const j=await api('/api/wifi/scan');const sel=$('#scan');"
"sel.innerHTML='<option value=\"\">— select an access point —</option>';"
"(j.aps||[]).forEach(a=>{const o=document.createElement('option');"
"o.value=JSON.stringify({ssid:a.ssid,bssid:a.bssid});"
"o.textContent=(a.ssid||'(hidden)')+' · '+(a.bssid||'')+' · '+(a.rssi+' dBm');"
"sel.appendChild(o)});"
"const n=(j.aps&&j.aps.length)||0;"
"st.textContent=n?(n+' APs — pick strongest CREA SPACE if mesh'):'No APs found';"
"}catch(e){st.textContent='Scan failed — reconnect SoftAP and retry';msg.className='msg err';"
"msg.textContent=e.message||String(e)}"
"btn.disabled=false};"
"$('#save').onclick=async()=>{const ssid=$('#ssid').value.trim(),msg=$('#msg');"
"if(!ssid){msg.className='msg err';msg.textContent='SSID required';return}"
"$('#save').disabled=true;msg.className='msg';msg.textContent='Connecting…';"
"try{await api('/api/wifi/save',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ssid,password:$('#password').value,bssid:$('#bssid').value.trim(),slot:'primary'})});"
"msg.className='msg ok';msg.textContent='Saved — SoftAP will stop when home Wi‑Fi succeeds. "
"Reconnect to home Wi‑Fi and open the gateway IP.';"
"}catch(e){msg.className='msg err';msg.textContent=e.message||String(e)}"
"$('#save').disabled=false};"
"</script></body></html>";
